03. web/Django/web_app2/blog/urls.py
from django.urls import path, re_path
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('', PostLV.as_view(), name='index'),
    # re_path(r'^(?P<slug>[-\w]+)/$', PostDV.as_view(), name='detail'),
    path('<int:pk>/', PostDV.as_view(), name='detail'),

    # /blog/archive/
    path('archive/archive/', PostAV.as_view(), name='post_archive'),
    # /blog/archive/2019/
    path('archive/<int:year>/', PostYAV.as_view(), name='post_year_archive'),
    # /blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', PostMAV.as_view(), name='post_month_archive'),
    # /blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', PostDAV.as_view(), name='post_day_archive'),
    # /blog/archive/today/
    path('archive/today/', PostTAV.as_view(), name='post_today_archive'),
    # Example: /blog/tag/
    path('tag/', TagCloudTV.as_view(), name='tag_cloud'),
    # Example: /blog/tag/tagname/
    path('tag/<str:tag>/', TaggedObjectLV.as_view(), name='tagged_object_list'),
    # Example: /blog/search/
    path('search/', SearchFormView.as_view(), name='search'),

     # Example: /blog/add/
    path('add/', PostCreateView.as_view(), name="add"),
    # Example: /blog/99/update/
    path('<int:pk>/update/', PostUpdateView.as_view(), name="update"),
    # Example: /blog/99/delete/
    path('<int:pk>/delete/', PostDeleteView.as_view(), name="delete"),

    path('download/<int:id>', download, name="download"),
]

03. web/Django/web_app2/blog/templates/blog/post_all.html
{% extends "base.html" %}

{% block title %}post_all.html{% endblock %}

{% block content %}
<h1>Blog List</h1>
<br>
{% for post in posts %}
<h3><a href="{{post.get_absolute_url}}">{{post.title}}</a></h3>
{{post.modify_dt|date:"Y-m-d"}}
<p>{{post.description}}</p>
{% endfor %}
<br>
<div>
    <span>
        {% if page_obj.has_previous %}
        <a href="?page={{page_obj.previous_page_number}}">Prev</a>
        {% endif %}

        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

        {% if page_obj.has_next %}
        <a href="?page={{page_obj.next_page_number}}">Next</a>
        {% endif %}
    </span>
</div>
<br>
{% include "pagination.html" %}

{% if user.is_active %}
    <div class="text-right mr-3">
        <a href="{%url 'blog:add' %}" class="btn btn-primary btn-sm">
            <i class="fas fa-pencil-alt"></i> 쓰기</a>
    </div>
{% endif %}

{% endblock %}

03. web/Django/web_app2/blog/templates/blog/post_archive.html
{% extends "base.html" %}

{% block title %}post_archive.html{% endblock %}

{% block content %}
<h1>Post Archives until {% now "b d, Y" %}</h1>
<ul>
    {% for date in date_list %}
    <li style="display: inline">
        <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">
            Year-{{ date|date:"Y" }}
        </a>
    </li>
    {% endfor %}
</ul>
<br/>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}">
                <strong>{{ post.title }}</strong>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

03. web/Django/web_app2/blog/templates/blog/post_archive_day.html
{% extends "base.html" %}

{% block title %}post_archive_day.html{% endblock %}

{% block content %}
<h1>Post Archive for {{ day|date:"N d, Y" }}</h1>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}">
                <strong>{{ post.title }}</strong>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

03. web/Django/web_app2/blog/templates/blog/post_archive_month.html
{% extends "base.html" %}

{% block title %}post_archive_month.html{% endblock %}

{% block content %}
<h1>Post Archive for {{ month|date:"N, Y" }}</h1>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}">
                <strong>{{ post.title }}</strong>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

03. web/Django/web_app2/blog/templates/blog/post_archive_today.html
<h1>Post Archive for {{ day|date:"N d, Y" }}</h1>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}">
                <strong>{{ post.title }}</strong>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>

03. web/Django/web_app2/blog/templates/blog/post_archive_year.html
{% extends "base.html" %}

{% block title %}post_archive_year.html{% endblock %}

{% block content %}
<h1>Post Archive for {{ year|date:"Y" }}</h1>

<ul>
    {% for date in date_list %}
    <li style="display: inline">
        <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'m' %}">
            {{ date|date:"F" }}
        </a>
    </li>
    {% endfor %}
</ul>
<br>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}">
                <strong>{{ post.title }}</strong>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

03. web/Django/web_app2/blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %}
{% block title %}post_confirm_delete.html{% endblock %}
{% block content %}
<h1>Post Delete</h1>
<br>
<form action="." method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}" ?</p>
    <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
</form>
{% endblock %}

03. web/Django/web_app2/blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block title %}post_detail.html{% endblock %}

{% block content %}
<h2>{{ object.title }}</h2>

<!-- <p>{{object.modify_dt | date:"Y-m-d"}}</p>
<p>작성자: {{object.owner.username}}</p> -->

<div class="text-right">작성자: {{object.owner}}
    <br>
    조회수: {{ object.read_cnt }}
    <br>
    수정일: {{ object.modify_dt|date:"Y년 m월 d일" }}
</div>

<div class="text-right my-3">
    {% for file in object.files.all %}
    <a href="{%url 'blog:download' file.id%}" class="ml-4">
        <i class="fas fa-download"></i>
        {{file.filename}} ({{file.size | filesizeformat}}) </a>
    {% endfor %}
</div>
    

<div>
    {{object.content | safe}}
</div>

<p>
    {% if object.get_previous %}
    <a href="{{object.get_previous.get_absolute_url}}" title="이전 글">prev</a>
    {% endif %}

    {% if object.get_next %}
    <a href="{{object.get_next.get_absolute_url}}" title="다음 글">next</a>
    {% endif %}
</p>

<br>
<div>
    <b>TAGS</b> <i class="fas fa-tag"></i>
    {% load taggit_templatetags2_tags %}
    {% get_tags_for_object object as "tags" %}
    
    {% for tag in tags %}
    <a href="{% url 'blog:tagged_object_list' tag.name %}">{{tag.name}}</a>
    {% endfor %}
    &emsp;<a href="{% url 'blog:tag_cloud' %}">
        <span class="btn btn-info btn-sm">TagCloud</span> </a>
</div>

{% if user == object.owner %}
    <div class="text-right">
        <a href="{% url 'blog:update' post.id %}" class="mr-3">
        <i class="far fa-edit"></i> 수정</a>
        <a href="{% url 'blog:delete' post.id %}" class="text-danger mr-3">
        <i class="fas fa-trash"></i> 삭제</a>
    </div>
{% endif %}
   
{% endblock %}

03. web/Django/web_app2/blog/templates/blog/post_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}post_form.html{% endblock %}

{% block content %}
<h1>Post Create/Update - {{user}}</h1>
<p class="font-italic">This is a creation or update form for your post.</p>
{% if form.errors %}
<div class="alert alert-danger">
    <div class="font-weight-bold">
        Wrong! Please correct the error(s) below.</div>
    {{ form.errors }}
</div>
{% endif %}
<form action="." method="post" enctype="multipart/form-data" class="card pt-3">{% csrf_token %}
    <div class="form-group row">
        {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
        <div class="col-sm-5">
            {{ form.title|add_class:"form-control"|attr:"autofocus" }}
        </div>
    </div>
    <div class="form-group row">
        {{ form.slug|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
        <div class="col-sm-5">
            {{ form.slug|add_class:"form-control"|attr:"readonly" }}
        </div>
        <small class="form-text text-muted">{{ form.slug.help_text }}</small>
    </div>
    <div class="form-group row">
        {{ form.description|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
        <div class="col-sm-5">
            {{ form.description|add_class:"form-control" }}
        </div>
        <small class="form-text text-muted">
            {{ form.description.help_text }}</small>
    </div>
    <div class="form-group row">
        <label for="files" class="col-form-label col-sm-2 ml-3 font-weight-bold">첨부 파일 :</label>
        <div class="col-sm-8 ">
            <input type="file" id="files" name="files" multiple>
        </div>
    </div>
    <div class="text-right">작성자: {{post.owner}} / 조회수: {{post.read_cnt}} / 수정일: {{ post.modify_dt|date:"Y년 m월 d일" }}</div>
    <div class="form-group row">
        <label for="files" class="col-form-label col-sm-2 ml-3 font-weight-bold">
            삭제할 파일 :</label>
        <div class="col-sm-8 ">
            {% for file in post.files.all %}
            <input type="checkbox" name="delete_files" value="{{file.id}}">
            {{file.filename}} ({{file.size | filesizeformat}})
            <br>
            {%endfor %}
        </div>
    </div>
    
    <div class="form-group row">
        {{ form.content|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
        <div class="col-sm-8">
            {{ form.content|add_class:"form-control" }}
        </div>
    </div>

    <div class="form-group row">
        {{ form.tags|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
        <div class="col-sm-5">
            {{ form.tags|add_class:"form-control" }}
        </div>
        <small class="form-text text-muted">{{ form.tags.help_text }}</small>
    </div>
    <div class="form-group">
        <div class="offset-sm-2 col-sm-5">
            <input type="submit" value="Submit" class="btn btn-info" />
        </div>
    </div>

</form>
{% endblock %}

{% block extra-script %}
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script>
    tinymce.init({
        selector: 'textarea',
        menubar: false,
        statusbar: false,
        toolbar1: 'formatselect | bold italic strikethrough forecolor backcolor | link | alignleft aligncenter alignright alignjustify | numlist bullist outdent indent | removeformat'
    });
</script>
{% endblock %}

03. web/Django/web_app2/blog/templates/blog/post_search.html
{% extends "base.html" %}

{% block title %}post_search.html{% endblock %}

{% block content %}
<h1>Blog Search</h1>
<br>
<form action="." method="post"> {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn btn-primary btn-sm">
</form>
<br /><br />
{% if object_list %}
    {% for post in object_list %}
        <h2><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h2>
        {{ post.modify_dt|date:"N d, Y" }}
        <p>{{ post.description }}</p>
    {% endfor %}
{% elif search_term %}
<b><i>Search Word({{ search_term }}) Not Found !</i></b>
{% endif %}
{% endblock %}